const fs = require('fs');
const path = require('path');

const b192 = "iVBORw0KGgoAAAANSUhEUgAAAOAAAADgCAMAAADaWgIhAAAAA1BMVEUAAACnej3aAAAASElEQVR4nO3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC3AcUIAAH5KysXAAAAAElFTkSuQmCC";
const b512 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAA1BMVEUAAACnej3aAAABJ0lEQVR4nO3BAQEAAACCIP+vbjiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwZEegAAX+2kLMAAAAASUVORK5CYII=";

if (!fs.existsSync('public')) {
  fs.mkdirSync('public', {recursive: true});
}

fs.writeFileSync(path.join('public', 'logo192.png'), Buffer.from(b192, 'base64'));
fs.writeFileSync(path.join('public', 'logo512.png'), Buffer.from(b512, 'base64'));
fs.writeFileSync(path.join('public', 'favicon.ico'), Buffer.from(b192, 'base64'));
